from ScriptCollection.TFCPS.NodeJS.TFCPS_CodeUnitSpecific_NodeJS import TFCPS_CodeUnitSpecific_NodeJS_Functions, TFCPS_CodeUnitSpecific_NodeJS_CLI
from ScriptCollection.TFCPS.TFCPS_VisualRegressionTests import TFCPS_VisualRegressionTests
import os
import shutil

# Maps the name a testcase gives its reference-image (see "saveReferenceImage" in "e2e/support/VisualRegression.ts")
# to the filename it gets in the readme.
_reference_images: dict[str, str] = {
    "country-selector-closed": "CountrySelectorClosed.png",
    "country-selector-open": "CountrySelectorOpen.png",
}


def update_readme_pictures(tf: TFCPS_CodeUnitSpecific_NodeJS_Functions) -> None:
    """
    Copies the reference-images which the visual-regression-testcases wrote while the baselines were regenerated
    into the readme image location. The testcases run inside the playwright-container, which only has the
    codeunit-folder mounted and can therefore not write into the repository-level "Other"-folder directly; this
    is the step which moves the images there. The images themselves already show only the component (see
    "saveReferenceImage" in "e2e/support/VisualRegression.ts"), so no cropping is done here.
    """
    source_folder: str = os.path.join(tf.get_artifacts_folder(), "ReferenceImages")
    target_folder: str = os.path.join(tf.get_repository_folder(), "Other", "Reference", "Technical", "Images")
    os.makedirs(target_folder, exist_ok=True)
    for source_name, target_name in _reference_images.items():
        source_path: str = os.path.join(source_folder, f"{source_name}.png")
        if not os.path.isfile(source_path):
            raise FileNotFoundError(f"The reference-image \"{source_path}\" was not generated by the visual-regression-testcases.")
        shutil.copyfile(source_path, os.path.join(target_folder, target_name))


def update_visual_regression_baselines() -> None:
    tf: TFCPS_CodeUnitSpecific_NodeJS_Functions = TFCPS_CodeUnitSpecific_NodeJS_CLI.parse(__file__)
    TFCPS_VisualRegressionTests(tf).run(True)
    update_readme_pictures(tf)


if __name__ == "__main__":
    update_visual_regression_baselines()
