from ScriptCollection.GeneralUtilities import GeneralUtilities
from ScriptCollection.TFCPS.Flutter.TFCPS_CodeUnitSpecific_Flutter import TFCPS_CodeUnitSpecific_Flutter_Functions, TFCPS_CodeUnitSpecific_Flutter_CLI
from VisualRegressionContainer import run_visual_regression_tests
import os
import shutil

# Maps the name a testcase gives its reference-image (see "_saveReferenceImage" in
# "test/visual_regression/visual_regression.dart") to the filename it gets in the readme.
_reference_images: dict[str, str] = {
    "toggle_button_light": "ToggleButtonLight.png",
    "toggle_button_dark": "ToggleButtonDark.png",
}


def update_readme_pictures(tf: TFCPS_CodeUnitSpecific_Flutter_Functions) -> None:
    """
    Copies the reference-images which the visual-regression-testcases wrote while the baselines were regenerated
    into the readme image location. The testcases run inside the visual-regression-container, which only has the
    codeunit-folder mounted and can therefore not write into the repository-level "Other"-folder directly; this
    is the step which moves the images there. The images themselves already show only the widget (see
    "_saveReferenceImage" in "test/visual_regression/visual_regression.dart"), so no cropping is done here.
    """
    source_folder: str = os.path.join(tf.get_artifacts_folder(), "ReferenceImages")
    target_folder: str = os.path.join(tf.get_repository_folder(), "Other", "Reference", "Technical", "Images")
    GeneralUtilities.ensure_directory_exists(target_folder)
    for source_name, target_name in _reference_images.items():
        source_path: str = os.path.join(source_folder, f"{source_name}.png")
        if not os.path.isfile(source_path):
            raise FileNotFoundError(f"The reference-image \"{source_path}\" was not generated by the visual-regression-testcases.")
        shutil.copyfile(source_path, os.path.join(target_folder, target_name))


def update_visual_regression_baselines() -> None:
    tf: TFCPS_CodeUnitSpecific_Flutter_Functions = TFCPS_CodeUnitSpecific_Flutter_CLI.parse(__file__)
    run_visual_regression_tests(tf, True)
    update_readme_pictures(tf)


if __name__ == "__main__":
    update_visual_regression_baselines()
