@startuml CodeUnits-Overview
skinparam defaultFontName "DejaVu Sans"
title CodeUnits of NgxCountrySelector

[NgxCountrySelector]
note as NgxCountrySelectorNote
  ngx-country-selector is an angular-component which lets the user choose a country from a configurable list of countries.
end note
NgxCountrySelector .. NgxCountrySelectorNote


@enduml