import 'mat_country.dart';

/// Every country of ISO 3166-1, ordered by its english name.
///
/// This is the list [MatCountrySelector] offers unless the application passes its own one. It is data, not
/// logic: it states which countries exist and what they are called in english, and nothing else - no
/// continents, no currencies, no dialling-codes, no political statement about any of the entries. The names
/// are the english short names of the standard itself, which is why some of them read as formally as they do
/// ("Bolivia (Plurinational State of)").
///
/// Generated from the published ISO-3166-1-list rather than typed by hand, and to be regenerated the same way
/// when the standard changes.
const List<MatCountry> allCountries = <MatCountry>[
  MatCountry(code: 'AF', name: 'Afghanistan'),
  MatCountry(code: 'AL', name: 'Albania'),
  MatCountry(code: 'DZ', name: 'Algeria'),
  MatCountry(code: 'AS', name: 'American Samoa'),
  MatCountry(code: 'AD', name: 'Andorra'),
  MatCountry(code: 'AO', name: 'Angola'),
  MatCountry(code: 'AI', name: 'Anguilla'),
  MatCountry(code: 'AQ', name: 'Antarctica'),
  MatCountry(code: 'AG', name: 'Antigua and Barbuda'),
  MatCountry(code: 'AR', name: 'Argentina'),
  MatCountry(code: 'AM', name: 'Armenia'),
  MatCountry(code: 'AW', name: 'Aruba'),
  MatCountry(code: 'AU', name: 'Australia'),
  MatCountry(code: 'AT', name: 'Austria'),
  MatCountry(code: 'AZ', name: 'Azerbaijan'),
  MatCountry(code: 'BS', name: 'Bahamas'),
  MatCountry(code: 'BH', name: 'Bahrain'),
  MatCountry(code: 'BD', name: 'Bangladesh'),
  MatCountry(code: 'BB', name: 'Barbados'),
  MatCountry(code: 'BY', name: 'Belarus'),
  MatCountry(code: 'BE', name: 'Belgium'),
  MatCountry(code: 'BZ', name: 'Belize'),
  MatCountry(code: 'BJ', name: 'Benin'),
  MatCountry(code: 'BM', name: 'Bermuda'),
  MatCountry(code: 'BT', name: 'Bhutan'),
  MatCountry(code: 'BO', name: 'Bolivia, Plurinational State of'),
  MatCountry(code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba'),
  MatCountry(code: 'BA', name: 'Bosnia and Herzegovina'),
  MatCountry(code: 'BW', name: 'Botswana'),
  MatCountry(code: 'BV', name: 'Bouvet Island'),
  MatCountry(code: 'BR', name: 'Brazil'),
  MatCountry(code: 'IO', name: 'British Indian Ocean Territory'),
  MatCountry(code: 'BN', name: 'Brunei Darussalam'),
  MatCountry(code: 'BG', name: 'Bulgaria'),
  MatCountry(code: 'BF', name: 'Burkina Faso'),
  MatCountry(code: 'BI', name: 'Burundi'),
  MatCountry(code: 'CV', name: 'Cabo Verde'),
  MatCountry(code: 'KH', name: 'Cambodia'),
  MatCountry(code: 'CM', name: 'Cameroon'),
  MatCountry(code: 'CA', name: 'Canada'),
  MatCountry(code: 'KY', name: 'Cayman Islands'),
  MatCountry(code: 'CF', name: 'Central African Republic'),
  MatCountry(code: 'TD', name: 'Chad'),
  MatCountry(code: 'CL', name: 'Chile'),
  MatCountry(code: 'CN', name: 'China'),
  MatCountry(code: 'CX', name: 'Christmas Island'),
  MatCountry(code: 'CC', name: 'Cocos (Keeling) Islands'),
  MatCountry(code: 'CO', name: 'Colombia'),
  MatCountry(code: 'KM', name: 'Comoros'),
  MatCountry(code: 'CG', name: 'Congo'),
  MatCountry(code: 'CD', name: 'Congo, Democratic Republic of the'),
  MatCountry(code: 'CK', name: 'Cook Islands'),
  MatCountry(code: 'CR', name: 'Costa Rica'),
  MatCountry(code: 'HR', name: 'Croatia'),
  MatCountry(code: 'CU', name: 'Cuba'),
  MatCountry(code: 'CW', name: 'Curaçao'),
  MatCountry(code: 'CY', name: 'Cyprus'),
  MatCountry(code: 'CZ', name: 'Czechia'),
  MatCountry(code: 'CI', name: 'Côte d\'Ivoire'),
  MatCountry(code: 'DK', name: 'Denmark'),
  MatCountry(code: 'DJ', name: 'Djibouti'),
  MatCountry(code: 'DM', name: 'Dominica'),
  MatCountry(code: 'DO', name: 'Dominican Republic'),
  MatCountry(code: 'EC', name: 'Ecuador'),
  MatCountry(code: 'EG', name: 'Egypt'),
  MatCountry(code: 'SV', name: 'El Salvador'),
  MatCountry(code: 'GQ', name: 'Equatorial Guinea'),
  MatCountry(code: 'ER', name: 'Eritrea'),
  MatCountry(code: 'EE', name: 'Estonia'),
  MatCountry(code: 'SZ', name: 'Eswatini'),
  MatCountry(code: 'ET', name: 'Ethiopia'),
  MatCountry(code: 'FK', name: 'Falkland Islands (Malvinas)'),
  MatCountry(code: 'FO', name: 'Faroe Islands'),
  MatCountry(code: 'FJ', name: 'Fiji'),
  MatCountry(code: 'FI', name: 'Finland'),
  MatCountry(code: 'FR', name: 'France'),
  MatCountry(code: 'GF', name: 'French Guiana'),
  MatCountry(code: 'PF', name: 'French Polynesia'),
  MatCountry(code: 'TF', name: 'French Southern Territories'),
  MatCountry(code: 'GA', name: 'Gabon'),
  MatCountry(code: 'GM', name: 'Gambia'),
  MatCountry(code: 'GE', name: 'Georgia'),
  MatCountry(code: 'DE', name: 'Germany'),
  MatCountry(code: 'GH', name: 'Ghana'),
  MatCountry(code: 'GI', name: 'Gibraltar'),
  MatCountry(code: 'GR', name: 'Greece'),
  MatCountry(code: 'GL', name: 'Greenland'),
  MatCountry(code: 'GD', name: 'Grenada'),
  MatCountry(code: 'GP', name: 'Guadeloupe'),
  MatCountry(code: 'GU', name: 'Guam'),
  MatCountry(code: 'GT', name: 'Guatemala'),
  MatCountry(code: 'GG', name: 'Guernsey'),
  MatCountry(code: 'GN', name: 'Guinea'),
  MatCountry(code: 'GW', name: 'Guinea-Bissau'),
  MatCountry(code: 'GY', name: 'Guyana'),
  MatCountry(code: 'HT', name: 'Haiti'),
  MatCountry(code: 'HM', name: 'Heard Island and McDonald Islands'),
  MatCountry(code: 'VA', name: 'Holy See'),
  MatCountry(code: 'HN', name: 'Honduras'),
  MatCountry(code: 'HK', name: 'Hong Kong'),
  MatCountry(code: 'HU', name: 'Hungary'),
  MatCountry(code: 'IS', name: 'Iceland'),
  MatCountry(code: 'IN', name: 'India'),
  MatCountry(code: 'ID', name: 'Indonesia'),
  MatCountry(code: 'IR', name: 'Iran, Islamic Republic of'),
  MatCountry(code: 'IQ', name: 'Iraq'),
  MatCountry(code: 'IE', name: 'Ireland'),
  MatCountry(code: 'IM', name: 'Isle of Man'),
  MatCountry(code: 'IL', name: 'Israel'),
  MatCountry(code: 'IT', name: 'Italy'),
  MatCountry(code: 'JM', name: 'Jamaica'),
  MatCountry(code: 'JP', name: 'Japan'),
  MatCountry(code: 'JE', name: 'Jersey'),
  MatCountry(code: 'JO', name: 'Jordan'),
  MatCountry(code: 'KZ', name: 'Kazakhstan'),
  MatCountry(code: 'KE', name: 'Kenya'),
  MatCountry(code: 'KI', name: 'Kiribati'),
  MatCountry(code: 'KP', name: 'Korea, Democratic People\'s Republic of'),
  MatCountry(code: 'KR', name: 'Korea, Republic of'),
  MatCountry(code: 'KW', name: 'Kuwait'),
  MatCountry(code: 'KG', name: 'Kyrgyzstan'),
  MatCountry(code: 'LA', name: 'Lao People\'s Democratic Republic'),
  MatCountry(code: 'LV', name: 'Latvia'),
  MatCountry(code: 'LB', name: 'Lebanon'),
  MatCountry(code: 'LS', name: 'Lesotho'),
  MatCountry(code: 'LR', name: 'Liberia'),
  MatCountry(code: 'LY', name: 'Libya'),
  MatCountry(code: 'LI', name: 'Liechtenstein'),
  MatCountry(code: 'LT', name: 'Lithuania'),
  MatCountry(code: 'LU', name: 'Luxembourg'),
  MatCountry(code: 'MO', name: 'Macao'),
  MatCountry(code: 'MG', name: 'Madagascar'),
  MatCountry(code: 'MW', name: 'Malawi'),
  MatCountry(code: 'MY', name: 'Malaysia'),
  MatCountry(code: 'MV', name: 'Maldives'),
  MatCountry(code: 'ML', name: 'Mali'),
  MatCountry(code: 'MT', name: 'Malta'),
  MatCountry(code: 'MH', name: 'Marshall Islands'),
  MatCountry(code: 'MQ', name: 'Martinique'),
  MatCountry(code: 'MR', name: 'Mauritania'),
  MatCountry(code: 'MU', name: 'Mauritius'),
  MatCountry(code: 'YT', name: 'Mayotte'),
  MatCountry(code: 'MX', name: 'Mexico'),
  MatCountry(code: 'FM', name: 'Micronesia, Federated States of'),
  MatCountry(code: 'MD', name: 'Moldova, Republic of'),
  MatCountry(code: 'MC', name: 'Monaco'),
  MatCountry(code: 'MN', name: 'Mongolia'),
  MatCountry(code: 'ME', name: 'Montenegro'),
  MatCountry(code: 'MS', name: 'Montserrat'),
  MatCountry(code: 'MA', name: 'Morocco'),
  MatCountry(code: 'MZ', name: 'Mozambique'),
  MatCountry(code: 'MM', name: 'Myanmar'),
  MatCountry(code: 'NA', name: 'Namibia'),
  MatCountry(code: 'NR', name: 'Nauru'),
  MatCountry(code: 'NP', name: 'Nepal'),
  MatCountry(code: 'NL', name: 'Netherlands, Kingdom of the'),
  MatCountry(code: 'NC', name: 'New Caledonia'),
  MatCountry(code: 'NZ', name: 'New Zealand'),
  MatCountry(code: 'NI', name: 'Nicaragua'),
  MatCountry(code: 'NE', name: 'Niger'),
  MatCountry(code: 'NG', name: 'Nigeria'),
  MatCountry(code: 'NU', name: 'Niue'),
  MatCountry(code: 'NF', name: 'Norfolk Island'),
  MatCountry(code: 'MK', name: 'North Macedonia'),
  MatCountry(code: 'MP', name: 'Northern Mariana Islands'),
  MatCountry(code: 'NO', name: 'Norway'),
  MatCountry(code: 'OM', name: 'Oman'),
  MatCountry(code: 'PK', name: 'Pakistan'),
  MatCountry(code: 'PW', name: 'Palau'),
  MatCountry(code: 'PS', name: 'Palestine, State of'),
  MatCountry(code: 'PA', name: 'Panama'),
  MatCountry(code: 'PG', name: 'Papua New Guinea'),
  MatCountry(code: 'PY', name: 'Paraguay'),
  MatCountry(code: 'PE', name: 'Peru'),
  MatCountry(code: 'PH', name: 'Philippines'),
  MatCountry(code: 'PN', name: 'Pitcairn'),
  MatCountry(code: 'PL', name: 'Poland'),
  MatCountry(code: 'PT', name: 'Portugal'),
  MatCountry(code: 'PR', name: 'Puerto Rico'),
  MatCountry(code: 'QA', name: 'Qatar'),
  MatCountry(code: 'RO', name: 'Romania'),
  MatCountry(code: 'RU', name: 'Russian Federation'),
  MatCountry(code: 'RW', name: 'Rwanda'),
  MatCountry(code: 'RE', name: 'Réunion'),
  MatCountry(code: 'BL', name: 'Saint Barthélemy'),
  MatCountry(code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha'),
  MatCountry(code: 'KN', name: 'Saint Kitts and Nevis'),
  MatCountry(code: 'LC', name: 'Saint Lucia'),
  MatCountry(code: 'MF', name: 'Saint Martin (French part)'),
  MatCountry(code: 'PM', name: 'Saint Pierre and Miquelon'),
  MatCountry(code: 'VC', name: 'Saint Vincent and the Grenadines'),
  MatCountry(code: 'WS', name: 'Samoa'),
  MatCountry(code: 'SM', name: 'San Marino'),
  MatCountry(code: 'ST', name: 'Sao Tome and Principe'),
  MatCountry(code: 'SA', name: 'Saudi Arabia'),
  MatCountry(code: 'SN', name: 'Senegal'),
  MatCountry(code: 'RS', name: 'Serbia'),
  MatCountry(code: 'SC', name: 'Seychelles'),
  MatCountry(code: 'SL', name: 'Sierra Leone'),
  MatCountry(code: 'SG', name: 'Singapore'),
  MatCountry(code: 'SX', name: 'Sint Maarten (Dutch part)'),
  MatCountry(code: 'SK', name: 'Slovakia'),
  MatCountry(code: 'SI', name: 'Slovenia'),
  MatCountry(code: 'SB', name: 'Solomon Islands'),
  MatCountry(code: 'SO', name: 'Somalia'),
  MatCountry(code: 'ZA', name: 'South Africa'),
  MatCountry(code: 'GS', name: 'South Georgia and the South Sandwich Islands'),
  MatCountry(code: 'SS', name: 'South Sudan'),
  MatCountry(code: 'ES', name: 'Spain'),
  MatCountry(code: 'LK', name: 'Sri Lanka'),
  MatCountry(code: 'SD', name: 'Sudan'),
  MatCountry(code: 'SR', name: 'Suriname'),
  MatCountry(code: 'SJ', name: 'Svalbard and Jan Mayen'),
  MatCountry(code: 'SE', name: 'Sweden'),
  MatCountry(code: 'CH', name: 'Switzerland'),
  MatCountry(code: 'SY', name: 'Syrian Arab Republic'),
  MatCountry(code: 'TW', name: 'Taiwan, Province of China'),
  MatCountry(code: 'TJ', name: 'Tajikistan'),
  MatCountry(code: 'TZ', name: 'Tanzania, United Republic of'),
  MatCountry(code: 'TH', name: 'Thailand'),
  MatCountry(code: 'TL', name: 'Timor-Leste'),
  MatCountry(code: 'TG', name: 'Togo'),
  MatCountry(code: 'TK', name: 'Tokelau'),
  MatCountry(code: 'TO', name: 'Tonga'),
  MatCountry(code: 'TT', name: 'Trinidad and Tobago'),
  MatCountry(code: 'TN', name: 'Tunisia'),
  MatCountry(code: 'TM', name: 'Turkmenistan'),
  MatCountry(code: 'TC', name: 'Turks and Caicos Islands'),
  MatCountry(code: 'TV', name: 'Tuvalu'),
  MatCountry(code: 'TR', name: 'Türkiye'),
  MatCountry(code: 'UG', name: 'Uganda'),
  MatCountry(code: 'UA', name: 'Ukraine'),
  MatCountry(code: 'AE', name: 'United Arab Emirates'),
  MatCountry(code: 'GB', name: 'United Kingdom of Great Britain and Northern Ireland'),
  MatCountry(code: 'UM', name: 'United States Minor Outlying Islands'),
  MatCountry(code: 'US', name: 'United States of America'),
  MatCountry(code: 'UY', name: 'Uruguay'),
  MatCountry(code: 'UZ', name: 'Uzbekistan'),
  MatCountry(code: 'VU', name: 'Vanuatu'),
  MatCountry(code: 'VE', name: 'Venezuela, Bolivarian Republic of'),
  MatCountry(code: 'VN', name: 'Viet Nam'),
  MatCountry(code: 'VG', name: 'Virgin Islands (British)'),
  MatCountry(code: 'VI', name: 'Virgin Islands (U.S.)'),
  MatCountry(code: 'WF', name: 'Wallis and Futuna'),
  MatCountry(code: 'EH', name: 'Western Sahara'),
  MatCountry(code: 'YE', name: 'Yemen'),
  MatCountry(code: 'ZM', name: 'Zambia'),
  MatCountry(code: 'ZW', name: 'Zimbabwe'),
  MatCountry(code: 'AX', name: 'Åland Islands'),
];
