import os
import shutil

from ScriptCollection.TFCPS.Flutter.TFCPS_CodeUnitSpecific_Flutter import TFCPS_CodeUnitSpecific_Flutter_Functions, TFCPS_CodeUnitSpecific_Flutter_CLI
from VisualRegressionContainer import run_visual_regression_tests

# Maps the name a testcase gives its baseline-image (see "test/visual_regression/mat_country_selector_test.dart")
# to the filename it gets in the readme.
_baseline_images_for_the_readme: dict[str, str] = {
    "country_selector_closed": "CountrySelectorClosed.png",
    "country_selector_open": "CountrySelectorOpen.png",
}


def update_readme_pictures(tf: TFCPS_CodeUnitSpecific_Flutter_Functions) -> None:
    """
    Copies the baseline-images which the visual-regression-testcases just regenerated to the location the readme
    references them from. The baseline-images show the widget and nothing else (the testcases render it on a
    surface of its own size, see "visual_regression.dart"), so no cropping is done here.

    The readme-pictures are deliberately the very same images the visual-regression-tests compare against: a
    picture which is maintained separately would show a state of the widget which does not exist anymore as soon
    as the appearance changes, while this one can not drift apart from what the tests assert.
    """
    source_folder: str = os.path.join(tf.get_codeunit_folder(), "Other", "Resources", "VisualRegressionBaselines")
    target_folder: str = os.path.join(tf.get_codeunit_folder(), "Other", "Reference", "Technical", "Images")
    os.makedirs(target_folder, exist_ok=True)
    for source_name, target_name in _baseline_images_for_the_readme.items():
        source_path: str = os.path.join(source_folder, f"{source_name}.png")
        if not os.path.isfile(source_path):
            raise FileNotFoundError(f"The baseline-image \"{source_path}\" was not generated by the visual-regression-testcases.")
        shutil.copyfile(source_path, os.path.join(target_folder, target_name))


def update_visual_regression_baselines() -> None:
    tf: TFCPS_CodeUnitSpecific_Flutter_Functions = TFCPS_CodeUnitSpecific_Flutter_CLI.parse(__file__)
    run_visual_regression_tests(tf, True)
    update_readme_pictures(tf)


if __name__ == "__main__":
    update_visual_regression_baselines()
